[bot]
exts = [
    'jishaku',
    'cogs.dev',
    'cogs.help',
    'cogs.table',
    'cogs.errors',
    'cogs.events',
    'cogs.nisdev'
]
home = 
nisdev = 
welcome = 
TOKEN = 'paste your token here'

[database]
user = 
password = 
host = 'localhost'
database = 